spring:
  data:
    mongodb:
      uri: mongodb+srv://diegocarbone22_db_user:HmCzwBHkzlj5l3Q2@main.hn1yisr.mongodb.net
      database: fluxenture_db
  application:
    name: core
google:
  drive:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    refresh-token: ${GOOGLE_REFRESH_TOKEN}