spring:
  data:
    mongodb:
      uri: ${FLUX_DB}
      database: fluxenture_db
  application:
    name: core
google:
  drive:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    refresh-token: ${GOOGLE_REFRESH_TOKEN}