server:
  port: ${PORT:8080} # Railway inyecta el puerto acá
spring:
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      uri: ${FLUX_DB}
      database: fluxenture_db
  application:
    name: core
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
google:
  drive:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    refresh-token: ${GOOGLE_REFRESH_TOKEN}